#! /bin/sh

#================================================================================
#       loaders
#--------------------------------------------------------------------------------

include-file = 

#================================================================================
#       bspwm settings
#--------------------------------------------------------------------------------

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width        2
bspc config window_gap          6
bspc config single_monocle      true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gpick state=floating focus=on center=on
bspc rule -a thunar state=floating focus=on center=on
bspc rule -a Transmission-gtk state=floating focus=on center=on

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#2D2D2D"
bspc config active_border_color "#88cc44"
bspc config focused_border_color "#88cc44"
bspc config urgent_border_color "#FF4500"
bspc config presel_border_color "#88cc44"
bspc config presel_feedback_color "#88cc44"

#================================================================================
#       externals
#--------------------------------------------------------------------------------

xsetroot -cursor_name left_ptr &
sxhkd &
picom -b &
nitrogen --restore &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
pkill -9 polybar &> /dev/null
polybar -q top -c "$HOME/.config/polybar/hack/config.ini" &> /dev/null &
